language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - 2.7.1

script:
  - bundle exec rspec spec/
branches:
  only:
    - master
notifications:
  email: false
